# This is a basic workflow to help you get started with Actions

name: M3U generator

# Controls when the action will run. 
on:
  schedule:
    - cron: '*/10 * * * *'

    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: Config
        run: |
          git config --global user.email "seu_email_placeholder"
          git config --global user.name "seu_nome_de_usuario_placeholder"

          
          
      - name: Install bs4
        run: |
          pip install beautifulsoup4
          pip install requests
          pip install lxml
          sudo apt-get update
          sudo apt-get install ffmpeg


          
      - name: Main
        run: |
          curl https://geolocation.onetrust.com/cookieconsentpub/v1/geo/location --output minhalocalização.txt
          pwd
          chmod +x ARGENTINA.sh
          ./ARGENTINA.sh

        
      - name: Git Add
        run: |
          git add -A
          ls -la
      - name: Commit and Push
        run: |
          git commit -m "Updated links"
          git push
